# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='json_reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RouteID_Direction', models.CharField(max_length=100)),
                ('JourneyPatternID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('RouteID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('BaseTime', models.DateTimeField()),
                ('NumOfStop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('StopID', models.IntegerField(primary_key=True, serialize=False)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('TimeFromStart', models.DateTimeField()),
                ('BusLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TTM.Routes')),
            ],
        ),
    ]
